apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"app.k8s.io/v1beta1","kind":"Application","metadata":{"annotations":{"kubernetes-engine.cloud.google.com/icon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIIAAACCCAYAAACKAxD9AAAABGdBTUEAALGPC/xhBQAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAByBJREFUeNrtnc1vXFcZh5/33vmwO7E9sWMmJCUNStJCDC1VQpWIBasKypJdV6hCtCRUsOgGIbHlD2BBsoANFWuWbCoVhCiofEihiJakoU1o4yI3cdLUdjzje18W5zodCrZnPCfzld8jjSzZ8tG55z73Pefc+953zN0RItEQCIkgJIKQCEIiCIkgtqUUtbUzVsYpA4Z3pKGR41RZ5cd92Me+YAlrlHFScgyDLfu5+TfDcTISWpzzXCLsxFmr4czg1DHSbYb44xEpp8VV4IPoR3fGjHNtgq0zjbMXZwJIO2wlA+7gLAM37/72u2Z9kbdPWC83lPJnrZI59XKJQziP4MwDk4VgO189RoqTYVzNc97cyHmr8lN/L+YBXv+GlepVPp0ahzEeBGZxKoUIvmMPw3E0gUWMf+Q57yzdYanxc88UETYv5xKzScZJcp4EngLmgfW2wLo9TgpkOMuJcbGS8gt+YL/kR96KdYBzNabJeBr4Ks5+YE/Rt06vgLQ4nn/hvJokvNSo8SvgQ4nw0Yk8ADxZfI710FID2Ae8zjKvrXzTrtR+5qu9dO3WM2YzVVLgEeCLwOlenQKmgGWcP4ybCEmPIhwCvgZ8NkJfZoDj5JyqlTnYc2N1qhgLwBPAoUjjdQRnAafB9yzhh2YSIYjwALD/v36ze8rA3iI61Ho+sowUp4HzKWA64pjNAXO02EMLiVCwAax9bHG167Vn8f9plPsbLdJC1Frk+yUGTJMzRTY+92FiHIhHHuSkR6Hae1UqPha5j2WgxBg9wR82o73LFX0nUSaPLKu3tSsRxHghEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSIT/S+yXYMWIimBtn2HG7/ZWItwTCRKMJFJE2KyG1iTuK+wZsI7RZGp8Xo0ftoiwB5jHmYmgVVq0N0XcwqIVoI6zh5sd12qUCF3yEM4TwDGet1qPR5YAnwEeB+oR+7gPOAUs0ByfyaE0ZP2ZJlRoO8EGl/i2/XMj43bm5NV0+6vPAXfy3ElSA0v5HPAYoezfZMQ+zgIngGU2uMZz9jYJeZ6RJzawCysssI0M4w7nuq9TOUwibF5dNeArOEeAi6WEa6Uwx5d2+Gc3I0+MKjBXlP77AjARuZ8PAEdxJouI8w7O+4nRIlb9p+6jeigTDO8CrwBXAMzMvMPSuqUhjFIJcLj4PApcKxZ7nczHWXHiD+BRp4N2ysVUUwcWgBs414pFaTqg8doU4RLOKmds5d3b3HLvPDIMowjtzLWF9U6uNC9OxmQf+1gHqnxUHnAQkTQHEpxPEEoa1w/WeBm4Oi4ipMWqf9gX3LUh6cthQt3LDzEudCOCbjGPHzVCOePyKG8fRW9kRRStdLtekQjjSdfPaySCJJAIQiIIiSAkgpAIQiIIiSAkgpAIQiIIiSAkgpAIIg4lDcGucWAdWAaW2Dln0QlpZVVC8she4n5VsUQYEE1gEXgVeBnjBs4EW+ctbmAkOA3gKCEl/jFCEkm7KBJhhCJBE3gD+C3we+DPJNwip4pvcTLDOwcGzOJcBm4S8gsfJnzRuikijBZ3CCn2vybhPHBprUk6mdzNYrZtBGJxhcXGJJeThLdx3sL4Os5+TQ2jx03gAvAnzvkbAJMhV7AjPhl+tDhrr/kGTTMWgC8T/0Uc7RruMUvAKxh/5ztW3nUrP/FscY03ca4A17V9HD3WikXi9V5H78CL3ix2HTeKdiXCiC0WHcipRKjjYKy3LRwlwoiRAx5p9HKgRRfrDIkwPITdgUdraxBvUUsEIRGERBASQUiEe7R9zIlXFDR2exKhrzsGRQRFUUJOQeXuA+TemADmCTUhJcIIUcXYB8zQijB+zl7gIP2t+/Q/6Olj98zjnMZYosnru27leStnTY6nxrFBRwNFhN3RIDw2PsU6jV23knE8NZ4CPg+RJhlFhL6SEgp6nga+5c/ZBYOrGKs45S0XklYkrjgTudNIjJPAlwhpa0iE0V0wPgocNfgr8BvCo+Stcxa9yFk0DiShLPAx4BAMR2FvidBbZJgiVF+t4KywfUm7vMhnrBe7hNlhkUAixKEOnNzl/Qgkwngx8jeYtGsQEkFIBCERhEQQEkFIBCERhEQQEkFIBCERhEQQAxchQU8wh40USLes5XRPRDAyQok5MTy0gFaRGte3iLACvKexHxrKwCpwoyjA0TGlHiPCdZy/FB14kPBN6hs6HwNhAngfuAhcxLjdTxEuAy9i/A3ncYzZYm4yBvwu333E5lgbobbTS8AfcRa7asS9x/P1fTNucQTnBKGYZFpMORKhfyLkxZrg38DvOO9dT9e9iwBw1ibJmQWq0SoLiW51yAnFQJc4763BiCDu+/sIQiIIiSAkgpAIQiIIiSAkgpAIQiIIiSAkgri/+Q/aXcSzrpbC2QAAAABJRU5ErkJggg==","marketplace.cloud.google.com/deploy-info":"{\"partner_id\": \"click-to-deploy-containers\", \"product_id\": \"rabbitmq\", \"partner_name\": \"Google Click to Deploy\"}"},"labels":{"app.kubernetes.io/name":"rabbitmq-1"},"name":"rabbitmq-1","namespace":"rabbitmq"},"spec":{"assemblyPhase":"Pending","componentKinds":[{"group":"v1","kind":"ConfigMap"},{"group":"v1","kind":"PersistentVolumeClaim"},{"group":"apps/v1","kind":"StatefulSet"},{"group":"v1","kind":"Secret"},{"group":"v1","kind":"Service"},{"group":"v1","kind":"ServiceAccount"}],"descriptor":{"description":"RabbitMQ is an open source messaging system that implements the Advanced Message Queueing Protocol to serve a variety of messaging applications.\n\n# Support\nGoogle does not offer support for this solution. However, community support is available on\n[Stack Overflow](https://stackoverflow.com/questions/tagged/rabbitmq/).\nAdditional support is available on [community forums](https://groups.google.com/forum/#!forum/rabbitmq-users).","links":[{"description":"User Guide: Google Click to Deploy RabbitMQ","url":"https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/rabbitmq/README.md"},{"description":"RabbitMQ documentation","url":"https://www.rabbitmq.com/documentation.html"},{"description":"RabbitMQ Getting Started Tutorials","url":"https://www.rabbitmq.com/getstarted.html"}],"maintainers":[{"name":"Google Click to Deploy","url":"https://cloud.google.com/solutions/#click-to-deploy"}],"notes":"# Get authentication credentials for the cluster\n\n```shell\ngcloud container clusters get-credentials [CLUSTER_NAME] --zone [CLUSTER_ZONE]\n```\nwhere:\n* `[CLUSTER_NAME]` is the name of the cluster for this application\n* `[CLUSTER_ZONE]` is the zone, in which the cluster is operating\n\nPlease read [here](https://cloud.google.com/kubernetes-engine/docs/quickstart#get_authentication_credentials_for_the_cluster) for more information.\n\n\u003c!--- ALL THIS BELOW IS COPIED FROM README.MD --\u003e\n\n# Get the status of the cluster\n\nBy default, the application does not have an external IP address. To get the\nstatus of the cluster, use `kubectl` to execute `rabbitmqctl` on the master\nnode:\n\n```\nkubectl exec -it rabbitmq-1-rabbitmq-0 --namespace rabbitmq -- rabbitmqctl cluster_status\n```\n\n# Authorization\n\nThe default username is `rabbit`. Use `kubectl` to get the generated password:\n\n```shell\nkubectl get secret/rabbitmq-1-rabbitmq-secret \\\n  --namespace rabbitmq \\\n  --output=jsonpath='{.data.rabbitmq-pass}' | base64 --decode\n```\n\n# (Optional) Expose the RabbitMQ service externally\n\nBy default, the application does not have an external IP. To create an\nexternal IP address for the service, run the following command:\n\n```\nkubectl patch service/rabbitmq-1-rabbitmq-svc \\\n  --namespace rabbitmq \\\n  --patch '{\"spec\": {\"type\": \"LoadBalancer\"}}'\n```\n\n\u003e **NOTE:** It might take some time for the external IP to be provisioned.\n\n# Access RabbitMQ service\n\n**Option 1:** If you run your RabbitMQ cluster behind a LoadBalancer, run the\nfollowing command to get the external IP of the RabbitMQ service:\n\n```\nSERVICE_IP=$(kubectl get service/rabbitmq-1-rabbitmq-svc \\\n  --namespace rabbitmq \\\n  --output jsonpath='{.status.loadBalancer.ingress[0].ip}')\n\necho \"http://${SERVICE_IP}:15672\"\n```\n\nTo access the RabbitMQ management UI, open `http://[EXTERNAL-IP]:15672`, where\n`[EXTERNAL-IP]` is the output of the command above.\n\n**Option 2:** Use port forwarding:\n\n```\nkubectl port-forward svc/rabbitmq-1-rabbitmq-svc --namespace rabbitmq 15672\n```\n\nTo access the RabbitMQ management UI, open [http://127.0.0.1:15672](http://127.0.0.1:15672).\n\n\u003c!--- ALL THIS ABOVE IS COPIED FROM README.MD --\u003e","type":"RabbitMQ","version":"3.7.24-20200410-181207"},"info":[{"name":"RabbitMQ external IP","type":"Reference","valueFrom":{"serviceRef":{"name":"rabbitmq-1-rabbitmq-svc"}}},{"name":"RabbitMQ username","value":"rabbit"},{"name":"RabbitMQ password","type":"Reference","valueFrom":{"secretKeyRef":{"key":"rabbitmq-pass","name":"rabbitmq-1-rabbitmq-secret"}}},{"name":"Erlang cookie","type":"Reference","valueFrom":{"secretKeyRef":{"key":"rabbitmq-erlang-cookie","name":"rabbitmq-1-rabbitmq-secret"}}}],"selector":{"matchLabels":{"app.kubernetes.io/name":"rabbitmq-1"}}}}
    kubernetes-engine.cloud.google.com/icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIIAAACCCAYAAACKAxD9AAAABGdBTUEAALGPC/xhBQAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAByBJREFUeNrtnc1vXFcZh5/33vmwO7E9sWMmJCUNStJCDC1VQpWIBasKypJdV6hCtCRUsOgGIbHlD2BBsoANFWuWbCoVhCiofEihiJakoU1o4yI3cdLUdjzje18W5zodCrZnPCfzld8jjSzZ8tG55z73Pefc+953zN0RItEQCIkgJIKQCEIiCIkgtqUUtbUzVsYpA4Z3pKGR41RZ5cd92Me+YAlrlHFScgyDLfu5+TfDcTISWpzzXCLsxFmr4czg1DHSbYb44xEpp8VV4IPoR3fGjHNtgq0zjbMXZwJIO2wlA+7gLAM37/72u2Z9kbdPWC83lPJnrZI59XKJQziP4MwDk4VgO189RoqTYVzNc97cyHmr8lN/L+YBXv+GlepVPp0ahzEeBGZxKoUIvmMPw3E0gUWMf+Q57yzdYanxc88UETYv5xKzScZJcp4EngLmgfW2wLo9TgpkOMuJcbGS8gt+YL/kR96KdYBzNabJeBr4Ks5+YE/Rt06vgLQ4nn/hvJokvNSo8SvgQ4nw0Yk8ADxZfI710FID2Ae8zjKvrXzTrtR+5qu9dO3WM2YzVVLgEeCLwOlenQKmgGWcP4ybCEmPIhwCvgZ8NkJfZoDj5JyqlTnYc2N1qhgLwBPAoUjjdQRnAafB9yzhh2YSIYjwALD/v36ze8rA3iI61Ho+sowUp4HzKWA64pjNAXO02EMLiVCwAax9bHG167Vn8f9plPsbLdJC1Frk+yUGTJMzRTY+92FiHIhHHuSkR6Hae1UqPha5j2WgxBg9wR82o73LFX0nUSaPLKu3tSsRxHghEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSAQhEYREEBJBSIT/S+yXYMWIimBtn2HG7/ZWItwTCRKMJFJE2KyG1iTuK+wZsI7RZGp8Xo0ftoiwB5jHmYmgVVq0N0XcwqIVoI6zh5sd12qUCF3yEM4TwDGet1qPR5YAnwEeB+oR+7gPOAUs0ByfyaE0ZP2ZJlRoO8EGl/i2/XMj43bm5NV0+6vPAXfy3ElSA0v5HPAYoezfZMQ+zgIngGU2uMZz9jYJeZ6RJzawCysssI0M4w7nuq9TOUwibF5dNeArOEeAi6WEa6Uwx5d2+Gc3I0+MKjBXlP77AjARuZ8PAEdxJouI8w7O+4nRIlb9p+6jeigTDO8CrwBXAMzMvMPSuqUhjFIJcLj4PApcKxZ7nczHWXHiD+BRp4N2ysVUUwcWgBs414pFaTqg8doU4RLOKmds5d3b3HLvPDIMowjtzLWF9U6uNC9OxmQf+1gHqnxUHnAQkTQHEpxPEEoa1w/WeBm4Oi4ipMWqf9gX3LUh6cthQt3LDzEudCOCbjGPHzVCOePyKG8fRW9kRRStdLtekQjjSdfPaySCJJAIQiIIiSAkgpAIQiIIiSAkgpAIQiIIiSAkgpAIIg4lDcGucWAdWAaW2Dln0QlpZVVC8she4n5VsUQYEE1gEXgVeBnjBs4EW+ctbmAkOA3gKCEl/jFCEkm7KBJhhCJBE3gD+C3we+DPJNwip4pvcTLDOwcGzOJcBm4S8gsfJnzRuikijBZ3CCn2vybhPHBprUk6mdzNYrZtBGJxhcXGJJeThLdx3sL4Os5+TQ2jx03gAvAnzvkbAJMhV7AjPhl+tDhrr/kGTTMWgC8T/0Uc7RruMUvAKxh/5ztW3nUrP/FscY03ca4A17V9HD3WikXi9V5H78CL3ix2HTeKdiXCiC0WHcipRKjjYKy3LRwlwoiRAx5p9HKgRRfrDIkwPITdgUdraxBvUUsEIRGERBASQUiEe7R9zIlXFDR2exKhrzsGRQRFUUJOQeXuA+TemADmCTUhJcIIUcXYB8zQijB+zl7gIP2t+/Q/6Olj98zjnMZYosnru27leStnTY6nxrFBRwNFhN3RIDw2PsU6jV23knE8NZ4CPg+RJhlFhL6SEgp6nga+5c/ZBYOrGKs45S0XklYkrjgTudNIjJPAlwhpa0iE0V0wPgocNfgr8BvCo+Stcxa9yFk0DiShLPAx4BAMR2FvidBbZJgiVF+t4KywfUm7vMhnrBe7hNlhkUAixKEOnNzl/Qgkwngx8jeYtGsQEkFIBCERhEQQEkFIBCERhEQQEkFIBCERhEQQAxchQU8wh40USLes5XRPRDAyQok5MTy0gFaRGte3iLACvKexHxrKwCpwoyjA0TGlHiPCdZy/FB14kPBN6hs6HwNhAngfuAhcxLjdTxEuAy9i/A3ncYzZYm4yBvwu333E5lgbobbTS8AfcRa7asS9x/P1fTNucQTnBKGYZFpMORKhfyLkxZrg38DvOO9dT9e9iwBw1ibJmQWq0SoLiW51yAnFQJc4763BiCDu+/sIQiIIiSAkgpAIQiIIiSAkgpAIQiIIiSAkgri/+Q/aXcSzrpbC2QAAAABJRU5ErkJggg==
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "click-to-deploy-containers",
      "product_id": "rabbitmq", "partner_name": "Google Click to Deploy"}'
  creationTimestamp: "2020-04-11T20:26:11Z"
  generation: 138734
  labels:
    app.kubernetes.io/name: rabbitmq-1
  name: rabbitmq-1
  namespace: rabbitmq
  resourceVersion: "42461218"
  selfLink: /apis/app.k8s.io/v1beta1/namespaces/rabbitmq/applications/rabbitmq-1
  uid: af2b6db8-7c32-11ea-ac5d-42010a8001f0
spec:
  assemblyPhase: Success
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: PersistentVolumeClaim
  - group: apps/v1
    kind: StatefulSet
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
  - group: v1
    kind: ServiceAccount
  descriptor:
    description: |-
      RabbitMQ is an open source messaging system that implements the Advanced Message Queueing Protocol to serve a variety of messaging applications.

      # Support
      Google does not offer support for this solution. However, community support is available on
      [Stack Overflow](https://stackoverflow.com/questions/tagged/rabbitmq/).
      Additional support is available on [community forums](https://groups.google.com/forum/#!forum/rabbitmq-users).
    links:
    - description: 'User Guide: Google Click to Deploy RabbitMQ'
      url: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/rabbitmq/README.md
    - description: RabbitMQ documentation
      url: https://www.rabbitmq.com/documentation.html
    - description: RabbitMQ Getting Started Tutorials
      url: https://www.rabbitmq.com/getstarted.html
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    notes: |-
      # Get authentication credentials for the cluster

      ```shell
      gcloud container clusters get-credentials [CLUSTER_NAME] --zone [CLUSTER_ZONE]
      ```
      where:
      * `[CLUSTER_NAME]` is the name of the cluster for this application
      * `[CLUSTER_ZONE]` is the zone, in which the cluster is operating

      Please read [here](https://cloud.google.com/kubernetes-engine/docs/quickstart#get_authentication_credentials_for_the_cluster) for more information.

      <!--- ALL THIS BELOW IS COPIED FROM README.MD -->

      # Get the status of the cluster

      By default, the application does not have an external IP address. To get the
      status of the cluster, use `kubectl` to execute `rabbitmqctl` on the master
      node:

      ```
      kubectl exec -it rabbitmq-1-rabbitmq-0 --namespace rabbitmq -- rabbitmqctl cluster_status
      ```

      # Authorization

      The default username is `rabbit`. Use `kubectl` to get the generated password:

      ```shell
      kubectl get secret/rabbitmq-1-rabbitmq-secret \
        --namespace rabbitmq \
        --output=jsonpath='{.data.rabbitmq-pass}' | base64 --decode
      ```

      # (Optional) Expose the RabbitMQ service externally

      By default, the application does not have an external IP. To create an
      external IP address for the service, run the following command:

      ```
      kubectl patch service/rabbitmq-1-rabbitmq-svc \
        --namespace rabbitmq \
        --patch '{"spec": {"type": "LoadBalancer"}}'
      ```

      > **NOTE:** It might take some time for the external IP to be provisioned.

      # Access RabbitMQ service

      **Option 1:** If you run your RabbitMQ cluster behind a LoadBalancer, run the
      following command to get the external IP of the RabbitMQ service:

      ```
      SERVICE_IP=$(kubectl get service/rabbitmq-1-rabbitmq-svc \
        --namespace rabbitmq \
        --output jsonpath='{.status.loadBalancer.ingress[0].ip}')

      echo "http://${SERVICE_IP}:15672"
      ```

      To access the RabbitMQ management UI, open `http://[EXTERNAL-IP]:15672`, where
      `[EXTERNAL-IP]` is the output of the command above.

      **Option 2:** Use port forwarding:

      ```
      kubectl port-forward svc/rabbitmq-1-rabbitmq-svc --namespace rabbitmq 15672
      ```

      To access the RabbitMQ management UI, open [http://127.0.0.1:15672](http://127.0.0.1:15672).

      <!--- ALL THIS ABOVE IS COPIED FROM README.MD -->
    type: RabbitMQ
    version: 3.7.24-20200410-181207
  info:
  - name: RabbitMQ external IP
    type: Reference
    valueFrom:
      serviceRef:
        name: rabbitmq-1-rabbitmq-svc
  - name: RabbitMQ username
    value: rabbit
  - name: RabbitMQ password
    type: Reference
    valueFrom:
      secretKeyRef:
        key: rabbitmq-pass
        name: rabbitmq-1-rabbitmq-secret
  - name: Erlang cookie
    type: Reference
    valueFrom:
      secretKeyRef:
        key: rabbitmq-erlang-cookie
        name: rabbitmq-1-rabbitmq-secret
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-1
status:
  components:
  - link: /api/v1/namespaces/rabbitmq/secrets/rabbitmq-1-deployer-config
    name: rabbitmq-1-deployer-config
    status: Ready
  - link: /api/v1/namespaces/rabbitmq/serviceaccounts/rabbitmq-1-deployer-sa
    name: rabbitmq-1-deployer-sa
    status: Ready
  - link: /apis/apps/v1/namespaces/rabbitmq/statefulsets/rabbitmq-1-rabbitmq
    name: rabbitmq-1-rabbitmq
    status: Ready
  - link: /apis/apps/v1beta2/namespaces/rabbitmq/statefulsets/rabbitmq-1-rabbitmq
    name: rabbitmq-1-rabbitmq
    status: Ready
  - link: /apis/apps/v1beta1/namespaces/rabbitmq/statefulsets/rabbitmq-1-rabbitmq
    name: rabbitmq-1-rabbitmq
    status: Ready
  - link: /api/v1/namespaces/rabbitmq/configmaps/rabbitmq-1-rabbitmq-config
    name: rabbitmq-1-rabbitmq-config
    status: Ready
  - link: /api/v1/namespaces/rabbitmq/services/rabbitmq-1-rabbitmq-discovery
    name: rabbitmq-1-rabbitmq-discovery
    status: Ready
  - link: /api/v1/namespaces/stockapi/persistentvolumeclaims/rabbitmq-1-rabbitmq-pvc-rabbitmq-1-rabbitmq-0
    name: rabbitmq-1-rabbitmq-pvc-rabbitmq-1-rabbitmq-0
    status: Ready
  - link: /api/v1/namespaces/rabbitmq/persistentvolumeclaims/rabbitmq-1-rabbitmq-pvc-rabbitmq-1-rabbitmq-0
    name: rabbitmq-1-rabbitmq-pvc-rabbitmq-1-rabbitmq-0
    status: Ready
  - link: /api/v1/namespaces/stockapi/persistentvolumeclaims/rabbitmq-1-rabbitmq-pvc-rabbitmq-1-rabbitmq-1
    name: rabbitmq-1-rabbitmq-pvc-rabbitmq-1-rabbitmq-1
    status: Ready
  - link: /api/v1/namespaces/rabbitmq/persistentvolumeclaims/rabbitmq-1-rabbitmq-pvc-rabbitmq-1-rabbitmq-1
    name: rabbitmq-1-rabbitmq-pvc-rabbitmq-1-rabbitmq-1
    status: Ready
  - link: /api/v1/namespaces/rabbitmq/persistentvolumeclaims/rabbitmq-1-rabbitmq-pvc-rabbitmq-1-rabbitmq-2
    name: rabbitmq-1-rabbitmq-pvc-rabbitmq-1-rabbitmq-2
    status: Ready
  - link: /api/v1/namespaces/rabbitmq/secrets/rabbitmq-1-rabbitmq-secret
    name: rabbitmq-1-rabbitmq-secret
    status: Ready
  - link: /api/v1/namespaces/rabbitmq/serviceaccounts/rabbitmq-1-rabbitmq-serviceaccount-702f
    name: rabbitmq-1-rabbitmq-serviceaccount-702f
    status: Ready
  - link: /api/v1/namespaces/rabbitmq/services/rabbitmq-1-rabbitmq-svc
    name: rabbitmq-1-rabbitmq-svc
    status: Ready
  conditions:
  - lastTransitionTime: "2020-04-17T02:17:40Z"
    lastUpdateTime: "2020-04-17T02:17:40Z"
    message: all components ready
    reason: ComponentsReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-04-11T20:26:11Z"
    lastUpdateTime: "2020-04-11T20:26:11Z"
    message: No error seen
    reason: NoError
    status: "False"
    type: Error
