apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: stockstud-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: https
      protocol: HTTP
    hosts:
    - "*"
  - port:
      number: 443
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: stockstud
spec:
  hosts:
  - "*"
  gateways:
  - stockstud-gateway
  http:
  - match:
    - uri:
        prefix: /auth
    route:
    - destination:
        host: auth
        port:
          number: 8080
  - match:
    - uri:
        prefix: /stocks
    route:
    - destination:
        host: stockapi.stockapi.svc.cluster.local
        port:
          number: 8080
  - route:
    - destination: 
        host: frontend.frontend.svc.cluster.local
        port:
          number: 80
---